### PR TITLE
Ytck evo bugs

### LINKED ISSUE #564: EVO overwrites the satisfaction labels so that they all become the same label
The satisfaction values vary amongst the nodes when the result first comes out, but if we switch to EVO state, the labels are changed to be completely the same.

image

image

### PR DESCRIPTION
**Pull request by YanningTan**
Fix #564 and #551

### CODE REVIEW

File: leaf-ui/rappid-extensions/ConfigInspector.js [hunk 1]
```diff
@@ -185,6 +185,8 @@ var Config = Backbone.View.extend({
             }
         }
         this.model.destroy();
+        IntentionColoring.setColorMode("EVO", undefined);
```
Comment (YesugenB) [inline leaf-ui/rappid-extensions/ConfigInspector.js]: Is IntentionColoring still being used? I thought we were removing it from evoObjects

**Comment by YesugenB** [comment]
Maybe make a separate issue for the part of #551 that is not yet completed?

**Review by YesugenB — APPROVED** [review]
