### PR TITLE
Issue376 Fixed in LinkInspector

### LINKED ISSUE #376: In LinkInspector.js, evolving relationships that start with and/or should be able to end with and/or

### PR DESCRIPTION
**Pull request by Manarnz**
I fixed the bug that does not allow users to choose an end relationship when they select and/or as the begin.

### CODE REVIEW

File: leaf-ui/rappid-extensions/LinkInspector.js [hunk 1]
```diff
@@ -248,8 +253,7 @@ var LinkInspector = Backbone.View.extend({
             this.link.linkType = begin.toUpperCase();
             this.link.postType = 'NO';
 
-            $("#repeat-error").text("Saved!");
-            $("#repeat-error").css("color", "lightgreen");
+
```
Comment (leshghi) [inline leaf-ui/rappid-extensions/LinkInspector.js:248]: Remove extra line

File: leaf-ui/rappid-extensions/LinkInspector.js [hunk 2]
```diff
@@ -170,11 +170,16 @@ var LinkInspector = Backbone.View.extend({
             
         } else {
             //Verify if it is possible to remove the NB tag from source and target
-            if (!this.hasNBLink(source, this.cell) && this.hasNBTag(source)){
-                source.attr(".funcvalue/text", "");
+            if (!this.hasNBLink(source, this.cell) && !this.hasNBTag(source)){
```
Comment (leshghi) [inline leaf-ui/rappid-extensions/LinkInspector.js]: Lets talk about how to make sure these changes don't show up in your pull request since they should already be merged into backbone-refactor

**Review by leshghi — CHANGES_REQUESTED** [review]
This looks great to me - good fix! There is a new issue I found after your fix, which is that if you click away from the LinkInspector and then click back in, the link resets to a "null" value. However, I you did not create that bug, it was just uncovered after you fixed this one! I would recommend checking out the bug I just mentioned, and adding a descriptive Issue for it in our project board with screenshots if possible (I can show you how to do this if you want help). That way it will be documented for a future fix :) Awesome job again - just make the changes I mentioned and the Issue on github and then I'll re-review and you should be all set.

**Review by leshghi — APPROVED** [review]
Looks great! Make sure to chose "squash and merge" from the green merge button dropdown menu and then you should be all set!
