### PR TITLE
ElementInspector.js bug fixes

### LINKED ISSUE #464: For selected init value the "No Function" does not show up
For intentions when you select an init value the (selected) "No Function" does not show up
124210265-1caf7d80-dab9-11eb-8808-340cd3a03da0

### LINKED ISSUE #469: ElementInspector.js cleanup
Add switch to setEvolvingFunction() and set cell-attrs-text in script of ElementInspector

### PR DESCRIPTION
**Pull request by YesugenB**
Closes issues #464 and #469

### CODE REVIEW

File: leaf-ui/rappid-extensions/ElementInspector.js [hunk 1]
```diff
@@ -237,6 +237,8 @@ var ElementInspector = Backbone.View.extend({
     checkInitialSatValue: function() {
         // Set correct dropdown options for function type based on initial satisfaction value
         $('option').show(); // Clear the previous selection
+        // Initialize evolvingFunction so the function type can be set as 'NT'
+        this.intention.set('evolvingFunction', new EvolvingFunctionBBM([]));
```
Comment (leshghi) [inline leaf-ui/rappid-extensions/ElementInspector.js]: I think proper syntax is new EvolvingFunctionBBM({}) with curly brackets

File: leaf-ui/rappid-extensions/BackboneModelsIntention.js [hunk 2]
```diff
@@ -255,48 +255,64 @@ var IntentionBBM = Backbone.Model.extend({
...
+                case 'D':
+                    var seg =  new FunctionSegmentBBM({type: funcType, refEvidencePair: 'denied', startTP: '0', startAT: 0}); 
+                    break;
+                case 'UD':
+                    var seg =  new FunctionSegmentBBM({type: 'C', refEvidencePair: initValue, startTP: '0', startAT: 0}); 
+                    break;
+             }
+             this.getFuncSegments().push(seg);
+        } 
+        else if (funcType == 'RC' || funcType == 'CR' || funcType == 'MP' || funcType == 'MN' || funcType == 'SD' || funcType == 'DS') {
```
Comment (leshghi) [inline leaf-ui/rappid-extensions/BackboneModelsIntention.js]: You can actually get rid of this else if and put all the logic for all cases in one switch I believe

**Review by leshghi — APPROVED** [review]
Looks good - see comments and make the small changes before merging. I haven't tested it intensely yet but the code looks good to me

**Review by i-m-foster — APPROVED** [review]
