### PR TITLE
Fixing bugs in ElementInspector.js Drop Down Menus 

### LINKED ISSUE #569: Able to select monotonic negative from denied
Also able to select monotonic positive from satisfied (As of now we don't know what actions we took to get this issue, we found by playing around with the side bar. Will update when we get more info. 
Screen Shot 2021-09-11 at 1 23 31 PM

### LINKED ISSUE #578: For UD functions you can select (no value) as a segment satisfaction value, which you shouldn't be able to do

### LINKED ISSUE #581: For SD and DS functions the wrong options are disabled in the function drop down
Screen Shot 2021-09-17 at 4 17 06 PM

### PR DESCRIPTION
**Pull request by i-m-foster**
Closes #581 #578 and #569

### CODE REVIEW

File: leaf-ui/rappid-extensions/ElementInspector.js [hunk 1]
```diff
@@ -220,7 +220,7 @@ var ElementInspector = Backbone.View.extend({
             this.$('option[value=I]').prop('disabled', this.intention.getUserEvaluationBBM(0).get('assignedEvidencePair') === '0011');
             this.$('option[value=D]').prop('disabled', this.intention.getUserEvaluationBBM(0).get('assignedEvidencePair') === '1100');
             this.$('option[value=MP]').prop('disabled', this.intention.getUserEvaluationBBM(0).get('assignedEvidencePair') === '0011');
-            this.$('option[value=MN]').prop('disabled', this.intention.getUserEvaluationBBM(0).get('assignedEvidencePair') === '1100');
+            this.$('option[value=MN]').prop('disabled', this.intention.getUserEvaluationBBM(0).get('assignedEvidencePair') === '1100');
```
Comment (YesugenB) [inline leaf-ui/rappid-extensions/ElementInspector.js]: Delete extra space at end

**Review by YesugenB — APPROVED** [review]
😎

**Review by Domily11 — APPROVED** [review]
Very small things like taking out spaced and adding in semi-colons, otherwise it looks good!!
