### PR TITLE
Fixed evolving contribution logic.

### LINKED ISSUE #207: no/++ link in Single Path Analysis
The results from a no/++ link do not appear to be correct in the single path analysis mode.

### PR DESCRIPTION
**Pull request by amgrubb**
Fixes: no/++ link in Single Path Analysis #207

### CODE REVIEW

**Comment by amgrubb** [comment]
@Domily11 Can you give this a quick read and make sure all my pre and posts match and make sense.

File: leaf-analysis/src/simulation/CSPLinks.java [hunk 1]
```diff
@@ -54,16 +54,17 @@ private static void addForwardContribution(
...
 	   				PrimitiveConstraint postConstraint = null;
-	   				if(post != null)
+	   				if(post != null && post != ContributionType.NONE)
 	   					postConstraint = createForwardContributionConstraint(post, values[sourceID][t], values[targetID][t]);
-	   				if((pre != null) && (post != null))
+	   				
+	   				if(preConstraint != null && postConstraint != null)
 	   					constraints.add(new IfThenElse(new XgtY(refTP, timePoints[t]), preConstraint, postConstraint));
-	   				else if (pre != null)
+	   				else if (preConstraint != null)
```
Comment (Domily11) [inline leaf-analysis/src/simulation/CSPLinks.java:65]: As long as the usage of pre/postConstraint instead of pre and post is intentional think it's good

**Review by Domily11 — APPROVED** [review]

File: leaf-analysis/src/simulation/CSPLinks.java (hunk 1 above)
Comment (amgrubb) [reply leaf-analysis/src/simulation/CSPLinks.java:65]: Yup!
